[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_CONTACT_EMAIL,VITE_APPS_SCRIPT_URL"

[[redirects]]
  from = "/api/otp"
  to = "/.netlify/functions/otp"
  status = 200

[[redirects]]
  from = "/api/blogs"
  to = "/.netlify/functions/blogs"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
